/*
	SwiftyImages.swift
	
	Generated by SwiftyAssets 🦊 on 28/10/2020
	Copyright © 2020. All rights reserved.
*/

import UIKit

extension SwiftyAssets {
	class Images {
		static var apple1: UIImage {
			return UIImage(named: "apple1")!
		}

	}
}
