/*
	SwiftyColors.swift
	
	Generated by SwiftyAssets 🦊 on 28/10/2020
	Copyright © 2020. All rights reserved.
*/

import UIKit

extension SwiftyAssets {
	class Colors {
		static var think_different: UIColor {
			return UIColor(named: "think_different")!
		}
	}
}
