/*
	SwiftyStrings.swift
	

	Generated by SwiftyAssets 🦊 on 23/04/2021
	Copyright © 2021. All rights reserved.
*/

import Foundation

extension SwiftyAssets {
	class Strings {
		static var think_different: String {
			return NSLocalizedString("think_different", comment: "")
		}

	}
}
