/*
    SwiftyFonts.swift
    
    
    Generated by SwiftyAssets 🦊 on 23/04/2021
    Copyright © 2020, . All rights reserved.
*/

import Foundation

// swiftlint:disable force_unwrapping nesting
protocol SwiftyAssetsFontProtocol where Self: RawRepresentable, Self.RawValue == String {
    
}

extension SwiftyAssetsFontProtocol {
    var postScriptName: String {
        return self.rawValue
    }
}

extension SwiftyAssets {
    class Font {
        enum AppleGaramond: String, SwiftyAssetsFontProtocol {
            case regular = "AppleGaramond"
            case boldItalic = "AppleGaramond-BoldItalic"
            case italic = "AppleGaramond-Italic"
            case bold = "AppleGaramond-Bold"
        }
        
        enum AppleGaramondLight: String, SwiftyAssetsFontProtocol {
            case italic = "AppleGaramondLight-Italic"
            case regular = "AppleGaramondLight"
        }
    }
}

#if canImport(UIKit)
import UIKit

extension SwiftyAssetsFontProtocol {
    func font(withSize size: CGFloat) -> UIFont {
        return UIFont(name: self.postScriptName, size: size)!
    }
}
#endif

#if canImport(SwiftUI)
import SwiftUI

extension SwiftyAssetsFontProtocol {
    func font(withSize size: CGFloat) -> Font {
        return Font.custom(self.postScriptName, size: size)
    }

    func font(withSize size: CGFloat, relativeTo style: Font.TextStyle) -> Font {
        return Font.custom(self.postScriptName, size: size, relativeTo: style)
    }
}
#endif
// swiftlint:enable force_unwrapping nesting
