/*
    SwiftyColors.swift
    

    Generated by SwiftyAssets 🦊 on 23/04/2021
    Copyright © 2021. All rights reserved.
*/

#if canImport(UIKit)
import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
    class UIColors {
        static var think_different: UIColor {
            return UIColor(named: "think_different")!
        }
    }
}
// swiftlint:enable force_unwrapping
#endif

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension SwiftyAssets {
    class Colors {
        static var think_different: Color {
            return Color("think_different")
        }
    }
}
#endif
