/*
	SwiftyStrings.swift
	
	Generated by SwiftyAssets 🦊 on 06/10/2020
	Copyright © 2020. All rights reserved.
*/

import Foundation

extension SwiftyAssets {
	class Strings {
		static var apple: String {
			return NSLocalizedString("apple", comment: "")
		}

	}
}
