/*
    SwiftyImages.swift
    

    Generated by SwiftyAssets 🦊 on 23/04/2021
    Copyright © 2020, . All rights reserved.
*/

#if canImport(UIKit)
import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
    class UIImages {
        static var apple1: UIImage {
            return UIImage(named: "apple1")!
        }
    }
}
// swiftlint:enable force_unwrapping
#endif

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension SwiftyAssets {
    class Images {
        static var apple1: Image {
            return Image("apple1")
        }
    }
}
#endif
