/*
	SwiftyFonts.swift
	
	Generated by SwiftyAssets 🦊 on 06/10/2020
	Copyright © 2020. All rights reserved.
*/

import Foundation

protocol SwiftyAssetsFontProtocol {
	var postScriptName: String { get }
}

extension SwiftyAssets {
	class Font {
		enum AppleGaramondLight: String, SwiftyAssetsFontProtocol {
			case italic = "AppleGaramondLight-Italic"
			case regular = "AppleGaramondLight"

			var postScriptName: String {
				return self.rawValue
			}
		}

		enum AppleGaramond: String, SwiftyAssetsFontProtocol {
			case regular = "AppleGaramond"
			case boldItalic = "AppleGaramond-BoldItalic"
			case italic = "AppleGaramond-Italic"
			case bold = "AppleGaramond-Bold"

			var postScriptName: String {
				return self.rawValue
			}
		}
	}
}

#if canImport(UIKit)
import UIKit

extension SwiftyAssetsFontProtocol {
	func font(withSize size: CGFloat) -> UIFont {
		return UIFont(name: self.postScriptName, size: size)!
	}
}
#endif

#if canImport(SwiftUI)
import SwiftUI

extension SwiftyAssetsFontProtocol {
	func font(withSize size: CGFloat) -> Font {
		return Font.custom(self.postScriptName, size: size)
	}

	func font(withSize size: CGFloat, relativeTo style: Font.TextStyle) -> Font {
		return Font.custom(self.postScriptName, size: size, relativeTo: style)
	}
}
#endif
