/*
	SwiftyStrings.swift
	
	Generated by SwiftyAssets 🦊 on 28/10/2020
	Copyright © 2020. All rights reserved.
*/

import Foundation

extension SwiftyAssets {
	class Strings {
		static var think_different: String {
			return NSLocalizedString("think_different", comment: "")
		}

	}
}
